format: '&3&l』biome}'
time: 3
worlds:
  #配置要显示的世界名字，后面的值如果是false则用小提示防止
  - 'world:true'
  - 'DIM-1:false'
  - 'DIM1:false'
translateName:
  OCEAN: 海洋
  PLAINS: 平原
  DESERT: 沙漠
  EXTREME_HILLS: 极端山脉
  FOREST: 森林
  TAIGA: 针叶林
  SWAMPLAND: 沼泽地
  RIVER: 河流
  HELL: 地狱
  SKY: 天空
  FROZEN_OCEAN: 冻洋
  FROZEN_RIVER: 冻河
  ICE_FLATS: 冰原
  ICE_MOUNTAINS: 冰山
  MUSHROOM_ISLAND: 蘑菇岛
  MUSHROOM_ISLAND_SHORE: 蘑菇岛滩
  BEACHES: 海滩
  DESERT_HILLS: 沙漠丘陵
  FOREST_HILLS: 森林丘陵
  TAIGA_HILLS: 针叶林丘陵
  SMALLER_EXTREME_HILLS: 较小的极端山脉
  JUNGLE: 丛林
  JUNGLE_HILLS: 丛林丘陵
  JUNGLE_EDGE: 丛林边缘
  DEEP_OCEAN: 深海
  STONE_BEACH: 石滩
  COLD_BEACH: 冷海滩
  BIRCH_FOREST: 白桦树林
  BIRCH_FOREST_HILLS: 白桦树林丘陵
  ROOFED_FOREST: 带树冠的森林
  TAIGA_COLD: 寒冷的针叶林
  TAIGA_COLD_HILLS: 寒冷的针叶林丘陵
  REDWOOD_TAIGA: 红杉针叶林
  REDWOOD_TAIGA_HILLS: 红杉针叶林丘陵
  EXTREME_HILLS_WITH_TREES: 有树木的极端山脉
  SAVANNA: 热带草原
  SAVANNA_ROCK: 岩石草原
  MESA: 丛林山
  MESA_ROCK: 岩石丛林山
  MESA_CLEAR_ROCK: 清晰岩石高原
  VOID: 虚空
  MUTATED_PLAINS: 变异平原
  MUTATED_DESERT: 变异沙漠
  MUTATED_EXTREME_HILLS: 变异极端山脉
  MUTATED_FOREST: 变异森林
  MUTATED_TAIGA: 变异针叶林
  MUTATED_SWAMPLAND: 变异沼泽地
  MUTATED_ICE_FLATS: 变异冰原
  MUTATED_JUNGLE: 变异丛林
  MUTATED_JUNGLE_EDGE: 变异丛林边缘
  MUTATED_BIRCH_FOREST: 变异白桦树林
  MUTATED_BIRCH_FOREST_HILLS: 变异白桦树林丘陵
  MUTATED_ROOFED_FOREST: 变异带树冠的森林
  MUTATED_TAIGA_COLD: 变异寒冷的针叶林
  MUTATED_REDWOOD_TAIGA: 变异红杉针叶林
  MUTATED_REDWOOD_TAIGA_HILLS: 变异红杉针叶林丘陵
  MUTATED_EXTREME_HILLS_WITH_TREES: 变异有树木的极端山脉
  MUTATED_SAVANNA: 变异热带草原
  MUTATED_SAVANNA_ROCK: 变异岩石草原
  MUTATED_MESA: 变异丛林山
  MUTATED_MESA_ROCK: 变异岩石丛林山
  MUTATED_MESA_CLEAR_ROCK: 变异清晰岩石高原