#启动配置
#按照顺序配置，则是按照顺序，启动
#如果不配置则，不视作需要主动启动的脚本
#如果脚本配置了另一个依赖脚本，被依赖的脚本会被先加载

##
# scripts:
#   - '脚本包名.脚本类名'
#只填写，需要只指向main方法，或者是继承脚本插件类的脚本，其他的脚本类，不需要手动写
scripts:
  - 'example1/Example1'
  - 'example2/Example2'
